# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - name: Clone GitHub Repo
      uses: actions/checkout@v2
    - name: Install Node.js v${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: Install NPM packages (Clean installation)
      run: npm ci
    - name: Check for linting
      run: npm run lint
    - name: Run tests
      run: npm run test --if-present
